#!/bin/bash
path="$1";
if [[ "" == "$1" ]]; then
	exit 500;
fi
if [[ -f "$path" ]]; then
	path=$(dirname "$path");
fi
if [[ ! -d "$path" ]]; then
	exit 501;
fi
ismetadir=$(echo "$path"|grep -P "/\\.git(/|\$)"|wc -l);
if [[ "0" != "$ismetadir" ]]; then
	exit 502;
fi
git -C "$path" rev-parse;
